### ISSUE TITLE
Twitter embeds cut off

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2166]
NetNewsWire user reported this with this one feed — not sure if it’s widespread or not.

Same bug on Mac and on iOS. Might be a bug in the feed, but we should check it out.

https://www.balloon-juice.com/feed/

![Screen Shot 2020-07-01 at 5 19 03 PM](https://user-images.githubusercontent.com/1297121/86302936-21e49e80-bbbf-11ea-97f4-235055b56703.png)

![IMG_0243](https://user-images.githubusercontent.com/1297121/86302947-2e68f700-bbbf-11ea-816a-01f06d6644f3.jpg)

**Comment by Wevah** [comment]
I think I've seen some similar issues with Twitter embeds on other sites. I'll see if I can dig up how they worked around it.

**Comment by Wevah** [comment]
Do you remember what the reason was that we forced `iframe`s to have `height: auto !important`?

**Comment by Wevah** [comment]
Found another issue that was fixed on Mac release but seems to have never made it to master.

**Comment by vincode-io** [comment]
Was it for the youtube videos?

**Comment by Wevah** [comment]
It might have been: e183a5406c5b8216553fbf2b2ffd77e39309c6bd.

**Comment by Wevah** [comment]
> Do you remember what the reason was that we forced `iframe`s to have `height: auto !important`?

I ask this because removing that makes teh Twitter embeds work correctly. Alternatively it could just be added for iframes not from Twitter, but that seems like the wrong fix.

**Comment by Wevah** [comment]
Oh, looks like there's also 82f8951c9647b245a956cc1f7a20a1742f60de31 which also never made it to `master`. 🤦🏻‍♂️

**Comment by Wevah** [comment]
So yeah, #1833. The YouTube fixes! Good call.

**Comment by Paul-Theron** [comment]
Help! I use NetNewWire almost exclusively to follow finance Twitter account (I use a secondary app to generate RSS feeds for the people that I follow). A week ago disaster struck - the bottom is chopped off the content right hand reader view.  See example below.

Any tips on how to avoid this?

<img width="600" alt="Screenshot 2020-07-06 at 13 26 28" src="https://user-images.githubusercontent.com/67904862/86588651-663fb800-bf8c-11ea-9df9-9cceffbf67f1.png">

**Comment by vincode-io** [comment]
@Wevah are we sure that this isn’t a problem we also have on the mac-release branch?  We don’t want to release 5.0.4 if this is a problem there.

**Comment by Wevah** [comment]
I'll double check, but I pulled some of the fix for this one off of some commits to `mac-release`. If it's being reported there it's probably true, though.

**Comment by Wevah** [comment]
Ok, yep, this is still busted on `mac-release`. Fix incoming.

**Comment by Wevah** [comment]
Ok, yep, this is fixed on for 5.0.4.

**Comment by vincode-io** [comment]
Good news!

**Comment by Paul-Theron** [comment]
Good news indeed! You guys rock. When is 5.0.4 going to be published?

**Comment by vincode-io** [comment]
We're working on getting it out right now.  We don't have an exact release date set.

**Comment by vincode-io** [comment]
@Wevah We have a report that this isn’t fixed on the ios-release branch. Could you look into it?  I don’t know what we did to fix it.
