### ISSUE TITLE
Embedded YouTube player doesn't work (Error 153)

### ISSUE THREAD

**Issue by That-Human-Being** [Ranchero-Software/NetNewsWire#4860]
Basically whenever a feed item has a YouTube video attached to it like how most hackaday articles link to the YouTube video that the article is about, the embedded player shows up, but is unable to play the video (I've tried adjusting various settings but none of what I tried did anything)

![image](https://github.com/user-attachments/assets/a5bf979a-0ddd-446c-b795-1204dc819a62)

[The article the screenshot was taken of](https://hackaday.com/2025/12/01/necroprinting-isnt-as-bad-as-it-sounds/)

**Comment by brentsimmons** [comment]
What’s the URL of the feed? Which syncing system are you using? (iCloud, Feedbin, or…?)

**Comment by That-Human-Being** [comment]
URL is https://hackaday.com/blog/feed/
And currently I'm just syncing to "on my iPhone"

**Comment by johan456789** [comment]
https://developers.google.com/youtube/terms/required-minimum-functionality#embedded-player-api-client-identity

> API Clients that use the YouTube embedded player (including the YouTube IFrame Player API) must provide identification through the HTTP Referer request header. In some environments, the browser will automatically set HTTP Referer, and API Clients need only ensure they are not setting the [Referrer-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Referrer-Policy) in a way that suppresses the Referer value. YouTube recommends using strict-origin-when-cross-origin Referrer-Policy, which is already the default in many browsers.

This should fix it: https://stackoverflow.com/a/79805072/6306190

> You need to either add this header:
'Referrer-Policy': 'strict-origin-when-cross-origin'
> Or you can add the following to your embed element:
referrerpolicy='strict-origin-when-cross-origin'

**Comment by regeniaguenthurwag11-dot** [comment]
I encountered the same issue as well, the embedded player is not working. Perhaps Apple's native player could be an alternative option? I hope this issue gets fixed soon.

**Comment by 404erreurs** [comment]
Same problem here when using iCloud, all videos included in the articles have “error 153.”

**Comment by regeniaguenthurwag11-dot** [comment]
The surprising news is that NNW running on Mac has been updated to version 7.0, which brings visual updates to the liquid glass effect. However, it seems that support for embedded playback in YouTube is still not available. Given the nature of NNW's development, I believe this major update may still take a long time......

**Comment by made2k** [comment]
Edit: Oh sorry @johan456789, I missed your linked PR right above this comment. Looks like you got the same thing and you provided some additional context. Thanks!

I grabbed the code and ran a test with a feed article that had a YouTube embed that resulted in the same error 153.

The issue from what I could tell was the WebView's origin is not configured correctly for a YouTube load. @johan456789 I think you are right in that it's also necessary to set the referrer policy, but that almost seems like the responsibility of the feed that is embedding the video. May be worth modifying the HTML, but that didn't seem necessary for a few sites that embed YouTube videos I tested. 

I was able to achieve successful embeds by editing the following file

https://github.com/Ranchero-Software/NetNewsWire/blob/87518d8188e80354e9c6350afa067d92c6ea9e76/iOS/Article/WebViewController.swift#L618

and modifying it to 

```
let baseUrl: URL = .init(string: rendering.baseURL) ?? ArticleRenderer.page.baseURL
webView.loadHTMLString(html, baseURL: baseUrl)
```

The `ArticleRenderer.page.baseURL` currently resolves to the `NetNewsWire.app` on the users device. I don't know if there's a reason to load the HTML from the app's location vs the article's URL.

Would this break any existing functionality changing the webView's baseURL that anyone knows of? If not I hope this helps. I'd be happy to set up a PR if this seems to be a viable fix.

**Comment by SamirTalwar** [comment]
Regarding the referrer policy, that is indeed the responsibility of the feed itself. For FreshRSS, [the YouTube extension](https://github.com/FreshRSS/Extensions/tree/main/xExtension-YouTube) now sets this correctly in the `<iframe>` element.

We still need the fix that @made2k proposed on the NetNewsWire side, though, for the embedded video to load correctly without "Error 153".

I tried modifying the HTML in my feed (by editing the YouTube extension for FreshRSS) to include an `origin` query parameter as proposed in [one of the answers in the Stack Overflow thread](https://stackoverflow.com/a/79806694), but it didn't work for me.

**Comment by brentsimmons** [comment]
Fixed in 7.1.2.

**Comment by SamirTalwar** [comment]
The fix seems to have replaced "Error Code 153" with "Error Code 152 - 4", unfortunately.

I expect it's one step closer, and hopefully there's a minor change that will get it the rest of the way there.

**Comment by crankygeek** [comment]
I'm seeing this on my iOS devices and Mac. Currently Mac is on 7.1.3 and iOS is on 7.1.3. I sync via Feedbin. Interestingly, Feedbin's iOS client displays the video preview image and plays video in the app just fine.

It does seem slightly improved. Before, I had the generic error window as shown in the original report, but now I get a more Youtube-ish error (with their chrome). See attached screenshot.

This is one feed I see it with, but I do see it with all of them:
https://www.youtube.com/feeds/videos.xml?channel_id=UCEOXxzW2vU0P-0THehuIIeg

<img width="666" height="649" alt="Image" src="https://github.com/user-attachments/assets/8731f9e6-1996-44f8-8463-44c4df0f7d71" />
